### PR TITLE
Ross Nichols (Fatima) - Added additional_document.txt file

### PR DESCRIPTION
**Pull request by nichro02**
**Deliverable Submission**

Please describe your comfort and completeness levels before submitting.

Comfort Level (1-5): 3

Completeness Level (1-5): 5 (I think?)

Do you have any remaining questions about this deliverable?: Will it work?

### CODE REVIEW

**Comment by fatima3558** [comment]
I'm glad you feel confident about that assignment! It looks like you added a file but it doesn't contain the info that was requested. Re-read the README.md file to know what information you should put in the file. Once you’re done, you can push to github again, and the new code will show up automatically. Let me know when this is done!

**Comment by nichro02** [comment]
Resubmitting deliverable

**Comment by fatima3558** [comment]
nice work! marking complete ✅ feel free to close PR

**Comment by nichro02** [comment]
Closing pull request

**Pull request closed without merging**
